### ISSUE TITLE
Estandarizar los nombres de funciones

### ISSUE THREAD

**Issue by diegovalle** [Eflores89/inegiR#1]
Está genial este paquete. A la mejor conviene usar una de las guías para nombres en R:

http://adv-r.had.co.nz/Style.html
https://google-styleguide.googlecode.com/svn/trunk/Rguide.xml#identifiers

En vez de usar nombres como Serie_Inegi() cambiarla por serie_inegi()

**Comment by Eflores89** [comment]
Gracias por la sugerencia! Como se menciona en ambas guías, pasan las funciones a minúsculas [i.e. serie_inegi()] excepto YoY() que se me hace bastante intuitiva mantenerla así.
