### ISSUE TITLE
Problemas cuando la frecuencia es decenal

### ISSUE THREAD

**Issue by diegovalle** [Eflores89/inegiR#10]
Si visitas http://www3.inegi.org.mx//sistemas/api/indicadores/v1//Indicador/3103003001/09/en/true/xml/APIKEY la función serie_inegi no puede convertir la fecha porque la frecuencia "Decenal" no está dentro del if

También creo que sería mejor dejar las fechas anuales como enteros en vez de yearmon porque no tienen un mes correspondiente. Creo lo único que hay que hacer es agregarle decenal a este if y usar as.integer

```r
if (s$MetaData$Freq == "Anual" | s$MetaData$Freq == "Yearly" | 
            s$MetaData$Freq == "Annual" | s$MetaData$Freq == 
            "Quinquenal") {
            Fechas_Date <- as.Date(zoo::as.yearmon(x = paste0("01/", 
                Fechas), format = "%m/%Y"))
        }
```

**Comment by diegovalle** [comment]
También Bienal

**Comment by Eflores89** [comment]
Excelente punto, lo arreglo mañana! gracias.

**Comment by Eflores89** [comment]
Listo! 

Agregue el decenal y bienal al if. No quise cambiar el yearmon porque ***creo*** que algunas de las funciones de más alto nivel dependen de que sea fecha, y si cambio algo acá, me van a saltar problemas en las otras. Recuerdo que había decidido dejarlo en primero de enero y usar fechas...

Por lo pronto, quiero hacer un par de *wrappers* más antes de volver a subir a CRAN en otra versión (que por cierto si tienes alguna sugerencia de indicador o indicadores, para juntar al estilo `inflacion_general()` bienvenidos)
