### ISSUE TITLE
Marcar error cuando el API no tiene información a nivel municipio

### ISSUE THREAD

**Issue by diegovalle** [Eflores89/inegiR#11]
Cuando tratas de obtener información de indicadores que no tienen información a nivel de municipios el paquete te regresa un error. Un ejemplo de indicador sin info municipal sería:

http://www3.inegi.org.mx//sistemas/api/indicadores/v1//Indicador/6300000270/01001/es/true/json/[token]

El error que regresa el paquete es:

```r
serie_inegi("http://www3.inegi.org.mx//sistemas/api/indicadores/v1//Indicador/6300000270/01001/es/true/json/", token)
Error in `[.data.frame`(ldply(.data = s$Data$Serie, .fun = "[[", "TimePeriod"),  : 
  undefined columns selected 
```
El json que regresa el INEGI es: 

```json
{"ErrorCode":"100","ErrorDetails":"","ErrorInfo":"No se encontraron resultados"}
```

Creo sería bueno revisar que el json o xml no contenga "No se encontraron resultados" o algo así para que el paquete pueda poner un warning()

**Comment by Eflores89** [comment]
A excelente! Lo agrego en la próxima versión!

**Comment by Eflores89** [comment]
Listo! 

Cuando retorna un error, arroja un valor NULL y te da un warning con el error del sitio de INEGI: 

```
serie_inegi("http://www3.inegi.org.mx//sistemas/api/indicadores/v1//Indicador/6300000270/01001/es/true/json/", token)

NULL

Warning message:
In serie_inegi_json(serie, token, metadata, coercionar) :
  Error de INEGI: No se encontraron resultados
```
