### ISSUE TITLE
Unknown IO errorfailed to load external entity 

### ISSUE THREAD

**Issue by jsorsby** [Eflores89/inegiR#16]
Hola, he seguido las instrucciones tal cual están en tus guías, sin embargo me sale este error:

Error: 1: Unknown IO error2: failed to load external entity "http://www3.inegi.org.mx/sistemas/api/indicadores/v1//Indicador/216064/00000/es/false/xml/[Mi token]"

Al tratar de bajar cualquier serie como INPC <- serie_inegi(urlINPC, token)

**Comment by Eflores89** [comment]
Hola trata de usar el mismo URL en un browser. 

Si puedes verlo es un problema con el firewall de R (tu computadora no deja a R usar el puerto para descargar datos). En otras ocasiones es un cambio del lado de INEGI, pero si es una serie bastante usada esto es poco probable.
