### ISSUE TITLE
Versión 2.0 del API (la versión actual ya no funciona)

### ISSUE THREAD

**Issue by diegovalle** [Eflores89/inegiR#18]
Al parecer el INEGI liberó la versión 2.0 de su API sin avisarle a nadie y retiró algunos de los indicadores de la versión 1.0. De hecho el ejemplo de como usar el API de su [página](http://www.beta.inegi.org.mx/servicios/api_indicadores_1.0.html) ya no funciona

http://www3.inegi.org.mx/sistemas/api/indicadores/v1/Indicador/1002000001/01/es/false/json/[Aquí va tu Token]

usando serie_inegi regresa

```r
library(inegiR)
token = ""
urlINPC2 <- 
"http://www3.inegi.org.mx/sistemas/api/indicadores/v1//Indicador/1002000001/00000/es/false/xml/"
INPC <- serie_inegi(urlINPC2, token)
```
```
Error de INEGI: Ocurrio un error inesperado en la aplicacion, por favor informe al proveedor del servicio http://www.inegi.org.mx/inegi/contacto/default.aspx
```

Según la [página 2.0](http://www.beta.inegi.org.mx/servicios/api_indicadores.html) del API en la pestaña de "constructor de consultas" la nueva dirección es:

https://www.inegi.org.mx/app/api/indicadores/desarrolladores/jsonxml/INDICATOR/1002000001/es/01000/false/BISE/2.0/[Aquí va tu Token]?type=json

y regresa los datos, pero igual cambiaron el formato.

**Comment by Eflores89** [comment]
Acabo de meterme a esto. Que quilombo *enorme* 😨
