### ISSUE TITLE
Error in open.connection(con, "rb") : HTTP error 400.

### ISSUE THREAD

**Issue by Jorge-hercas** [Eflores89/inegiR#22]
Hola, he estado tratando de usar la función `inegi_bop(token = token1)` y `gdp <- inegi_series(serie = "381016", token = token1)` pero siempre obtengo ese error (token1 es el objeto con el token que obtuve de inegi). ¿Hay algo que estaré haciendo mal? Muchas gracias por leerme y buenas noches

**Comment by Eflores89** [comment]
Hola, el problema es de conectividad de tu computadora al internet o de INEGI para afuera (Error significa que no existe el URL). Sugiero tratar de acceder desde un browser al URL para que veas si el problema es tu conexion. INEGI tambíen a veces recategoriza las series con otros numeros...
