### ISSUE TITLE
Problema con inegi_bop()

### ISSUE THREAD

**Issue by MartinVernonFernandez** [Eflores89/inegiR#23]
Hola! Cuando intento usar la función inegi_bop(token), me aparece este error:
Error in parse_con(txt, bigint_as_char) : parse error: premature EOF

No parece ser un problema de conección, parece que el JSON que regresa la función no es legible o ha sido corrompido. Por ahora uso inegi_series_multiple() para extraer los datos necesarios, pero quería publicar el asunto para la próxima actualización. Gracias por su atención.

**Comment by Eflores89** [comment]
Hola martin, puedes ponerme algun ejemplo para reproducir el erorr?
