### ISSUE TITLE
Package check results comments

### ISSUE THREAD

**Issue by hrbrmstr** [Eflores89/inegiR#9]
- `Manual_inegiR.pdf` needs to be in `.Rbuildignore`
- `Denue_Inegi.R`, `FuncionesAuxiliares.R`, `FuncionesAuxiliares_denue.R`, `OtrosIndicadores.R` & `Serie_Inegi.R` all have non-ASCII characters in the code blocks (possibly in strings) and that won't get through CRAN. The Writing R Extensions manual shows how to still be able to use non-ASCII elements in strings in a portable fashion.
- CRAN holds packages to a higher standard than regular code, so for places like `grepl` where you use a partial patch (i.e. `pat=…`) you should switch those to full parameter name passing
- in any calls to `subset` (et al) you will need to use quoted character vectors vs bare strings or you'll need to handle them differently by adding a large `varname1 <- varname2 <- varname3 <- NULL` in one of the `.R` files. An example of the quoting would be ``subset(iris, `Species`=="setosa")``
- The `Catalogo_Inegi` data set needs to be documented (covered in Writing R documentation files)
- At least one of the example code chunks has non-ASCII characters in them (so you'll need to fix that as well)
- Any example code that relies on an external resource (e.g. a URL or API) should probably be either in a `\dontrun{}` block or have `tryCatch` error checking to ensure it won't fail on CRAN (it failed on my system)

A few of those elements aren't too difficult so if you can try to take a stab at them and then ping me again, I can try to help for the more gnarly ones (via pull requests or just more guidance).

Once this gets a bit further along I can also test it on an `r-devel` setup I have under Ubuntu & CentOS (as well as my Mac and my Windows system).

**Comment by Eflores89** [comment]
Thanks this is very helpful, i'll get to work on these.

**Comment by Eflores89** [comment]
@hrbrmstr hi, I think I was able to perform all the changes: 

- `Manual_inegiR.pdf` needs to be in `.Rbuildignore` 
  - ok 
- `Denue_Inegi.R`, et.al  non-ASCII 
  - ok 
-  partial patch (i.e. `pat=…`) y
  - ok (thoroughly checked manually, but i'm not sure if there are other cases).
- in any calls to `subset` (et al) you will need to use quoted character vectors vs bare strings 
  - I'm not sure if this is good practice, but per this: http://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when I added a new file: `CMDcheckVars.R`. This seems to pass the checks, but not sure if it is CRAN-worthy. 
- The `Catalogo_Inegi` data set needs to be documented (covered in Writing R documentation files)
  - deleted (no need to have it).
-  example codes 
  - ok (added `dontrun{}` in most of them).

**Comment by hrbrmstr** [comment]
Cool. I'll pull it down and give it a go again.

**Comment by hrbrmstr** [comment]
_Really_ nice job! Built & checked clean on OS X 10.11 / R 3.2.2. I'm doing an r-devel build/check now.

**Comment by hrbrmstr** [comment]
Worked perfectly on r-devel and on Windows. You should be good to go!

**Comment by Eflores89** [comment]
Thanks so much!
